Project: Terminator
TitleCanvas: Терминатор
WhoOnCanvas: Арнольд Шварценеггер
Video_file: Terminator.mov
tags: ['Terminator', 'Arnold Schwarzenegger', 'terminator', 'art', 'canvas paint',
        'canvas art', 'art work', 'art works', 'масляная живопись',
        'туториал', 'как нарисовать быстро', 'анимализм', 'кисти', 'разбавитель',
        'лайф хак', 'краски', 'зарисовка', 'видеоурок',
        'мастер класс', 'для начинающих художников', 'советы', 'холст', 'обучение',
        'как рисовать', 'художник', 'искусство', 'художественные материалы', 'онлайн урок',
        'Saatchi art',
        'фото реализм', 'пейзаж', 'дизайн интерьера', 'абстракция',
        'art', 'oil painting', 'tutorial',
        'landscape', 'картина маслом']
